### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by shivaabed1994** [NexvisionLab/Darkweb-search-engine#3]
And another question:
When ./web.sh run, I got some errors like this messages although python packages in .DockerFile installed. And if I want to install the package, it's not found.

Traceback (most recent call last):
File "/opt/torscraper/web-general/app.py", line 11, in
from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by NexvisionLab** [comment]
Hi @shivaabed1994 , would you checkout the latest commit and try again?

**Comment by labedinzade** [comment]
Done
