### ISSUE TITLE
[Warning] Aborted connection 4607 to db: 'tor' user: 'toruser' host: '172.16.57.18' (Got an error reading communication packets)

### ISSUE THREAD

**Issue by ghost** [NexvisionLab/Darkweb-search-engine#5]
Hi,
[Warning] Aborted connection 4607 to db: 'tor' user: 'toruser' host: '172.16.57.18' (Got an error reading communication packets)

I got this message from 'docker logs nexvisions-torscraper-db' command and the web doesn't work.
How can I resolve this?

**Comment by NexvisionLab** [comment]
Can you share the logs of nexvisions-torscraper-web-general?

**Comment by Fouty7** [comment]
Hi @NexvisionLab please how was this issue resolved? I am getting the same error. Do I share my logs?
