### ISSUE TITLE
Web search

### ISSUE THREAD

**Issue by saraabdi955** [NexvisionLab/Darkweb-search-engine#6]
Hi @NexvisionLab 
What is the final web output?
And how could it crawl a .onion link in localhost:7000?

**Comment by NexvisionLab** [comment]
`Models path: /opt/torscraper/lib/mordecai/models/`
` * Serving Flask app "app" (lazy loading)`
` * Environment: production`
`   WARNING: This is a development server. Do not use it in a production deployment.`
`   Use a production WSGI server instead.`
` * Debug mode: off`
` * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`
The final log output of web-general container should be like above.
So web-general is just a Flask based web console on which the user can search hiddenservice data.
scraper container crawls the onion domains through tor-proxy.
In project readme, please check how to run the scraper container and how to import initial domains.

**Comment by saraabdi955** [comment]
Hi again @NexvisionLab 
I saw this web page. But that was so simple and I only search for an item.
My question is:
I want to give a list of 1000 thousand dark web sites and this system will crawl them.
And show me the information of each site regularly. This site has this emails, bitcoins and etc. 
Is it possible?

**Comment by NexvisionLab** [comment]
When we extract emails for onion pages, we don't store the source page url for each email.
For bitcoin, we do save the source page url for each address.

**Comment by saraabdi955** [comment]
Ok!
